// todo-app/src/App.vue
<script lang="ts">
import TodoItem from './components/TodoItem.vue';
import TodoFooter from './components/TodoFooter.vue';
import TodoHeader from './components/TodoHeader.vue';
import TodoAdder from './components/TodoAdder.vue';
import TodoFooterMobile from './components/TodoFooterMobile.vue';
import draggable from 'vuedraggable';
import { v4 as uuidv4 } from 'uuid';
import { TodoItemType } from './types'


export default {

  data() {
    return {
      todoList: [
        { id: uuidv4(), label: "todo one", completed: true },
        { id: uuidv4(), label: "todo two", completed: false },
      ],
      filter: "All",
      lightTheme: false,
    }
  },
  components: {
    TodoItem: TodoItem,
    TodoFooter: TodoFooter,
    TodoHeader: TodoHeader,
    TodoAdder: TodoAdder,
    draggable: draggable,
    TodoFooterMobile
  },
  methods: {
    handleAddTodo(todo: TodoItemType) {
      this.todoList.push(todo)
    },
    handleDeleteTodo(todo: TodoItemType) {
      const findIndex = this.todoList.findIndex(a => a.id === todo.id)
      findIndex !== -1 && this.todoList.splice(findIndex, 1)
    },
    clearCompleted() {
      this.todoList = this.todoList.filter(item => !item.completed);
    },
    handleFilter(filter: string) {
      this.filter = filter
    },
    isShown(todo: TodoItemType) {
      if (this.filter == 'Completed') {
        return todo.completed
      } else if (this.filter == 'Active') {
        return !todo.completed
      } else {
        return true
      }
    }
  },
  mounted() {
    if (localStorage.todoList) {
      this.todoList = JSON.parse(localStorage.todoList)
    }
  },
  watch: {
    todoList: {
      handler(newValue) {
        localStorage.todoList = JSON.stringify(newValue);
      },
      deep: true
    }
  },
  computed: {
    remainingTodo() {
      return this.todoList.filter(item => !item.completed).length;
    },
  }
}

</script>

<template>
  <div :data-theme="lightTheme ? 'light' : 'dark'">
    <div class="app">
      <TodoHeader v-model="lightTheme" />
      <div class="todo-input">
        <TodoAdder @AddTodo="handleAddTodo" />
      </div>

      <div class="todo-list">
        <draggable v-model="todoList" item-key="id">
          <template #item="{ element: todo }">
            <TodoItem :item-data="todo" v-if="isShown(todo)" @delete="handleDeleteTodo" />
          </template>
        </draggable>
        <TodoFooter :remaining="remainingTodo" @ClearCompleted="clearCompleted" :filter="filter" @Filter="handleFilter" />
        <TodoFooterMobile :filter="filter" @Filter="handleFilter" />
      </div>

      <div class="hint-text">
        <span>Drag and drop to reorder list</span>
      </div>
    </div>
  </div>

  <div class="attribution">
    Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>.
    Coded by <a href="mailto:ismail.monsieur495@aleeas.com">C. ismail</a>.
  </div>
</template>

<style scoped>
.app {
  max-width: 530px;
  padding-inline: 25px;
  margin: 0 auto;
}

.todo-input .todo-item {
  border-radius: 5px;
  border: none;
}

.todo-input {
  margin-bottom: 30px;
}


.todo-list {}

.todo-list> :first-child {
  border-radius: 5px 5px 0 0;
}

.hint-text {
  margin-top: 60px;
  text-align: center;
}
</style>

// todo-app-reacte/src/App.tsx
import React, { useEffect, useState } from 'react';
import TodoList from './components/TodoList';
import AddTodo from './components/AddTodo';
import { v4 as uuidv4 } from 'uuid';
import './App.css';

export interface Todo {
  id: string;
  task: string;
  completed: boolean;
}


const App: React.FC = () => {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [darkMode, setDarkMode] = useState(true);
  const [filter, setFilter] = useState<boolean | string>(false)

  useEffect(() => {
    setFilter("all")
    const savedTodos = localStorage.getItem('todos');
    if (savedTodos) {
      setTodos(JSON.parse(savedTodos));
    }
    setLoaded(true);
  }, []);

  useEffect(() => {
    if (!loaded) return
    localStorage.setItem('todos', JSON.stringify(todos));
  }, [todos]);


  const addTodo = (task: string) => {
    const newTodo: Todo = { id: uuidv4(), task, completed: false };
    setTodos([...todos, newTodo]);
  };

  const removeTodo = (id: string) => {
    setTodos(todos.filter(todo => todo.id !== id));
  };

  const removeCompleted = () => {
    setTodos(todos.filter(todo => !todo.completed));
  };

  const toggleTodo = (id: string) => {
    setTodos(todos.map(todo =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  };

  const filtredList = () => {
    return filter == "all" ? todos : todos.filter(todo => todo.completed == filter)
  }

  const remaining = () => {
    return todos.filter(todo => !todo.completed).length
  }

  const updateTodo = (id: string, newValue: string) => {
    setTodos(todos.map(todo =>
      todo.id === id ? { ...todo, task: newValue } : todo
    ));
  }

  return (
    <div data-theme={darkMode ? "dark" : "light"}>
      <div className="app">

        <header>
          <h1>TODO</h1>
          <label htmlFor="darkModeToggle" className="darkmode-switch">
            <input aria-label="switch-theme" type="checkbox" id="darkModeToggle"
              onClick={() => setDarkMode(!darkMode)}
            />
            <span className="checkbox-icon"></span>
          </label>
        </header>

        <div className="todo-input">
          <AddTodo addTodo={addTodo} />
        </div>



        <TodoList todos={filtredList()} removeTodo={removeTodo} toggleTodo={toggleTodo} setTodos={setTodos} updateTodo={updateTodo} />

        <div className="todo-footer">
          <span> {remaining()}  items left</span>
          <div className="filter">
            <button onClick={() => setFilter('all')} className={(filter == 'all') ? 'selected' : ""} >All</button>
            <button onClick={() => setFilter(false)} className={!filter ? 'selected' : ""} >Active</button>
            <button onClick={() => setFilter(true)} className={filter == true ? 'selected' : ""} >Completed</button>
          </div>
          <button onClick={removeCompleted} >Clear completed</button>
        </div>


        <div className="hint-text">
          <span>Drag and drop to reorder list</span>
        </div>


        <div className="attribution">
          Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>.
          Coded by <a href="mailto:ismail.monsieur495@aleeas.com">C. ismail</a>.
        </div>
      </div>
    </div>
  );
};

export default App;
